# Generated by Django 2.2.14 on 2020-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20201201_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
