# Generated by Django 2.2.14 on 2020-12-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Suitcase', 'Suitcase'), ('Straws', 'Straws'), ('Plates', 'Plates'), ('Pen', 'Pen'), ('Towel', 'Towel'), ('Brush', 'Brush')], default='', max_length=100),
        ),
    ]
