# Generated by Django 2.2.14 on 2020-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
