# Generated by Django 2.2.14 on 2020-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20201201_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
