# Generated by Django 2.2.14 on 2020-12-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20201201_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.CharField(choices=[('Above 10,00,000', 'Above 10,00,000'), ('Above 5,00,000', 'Above 5,00,000'), ('Below 5 Lakh', 'Below 5 Lakh')], default='', max_length=100),
        ),
    ]
