# Generated by Django 2.2.14 on 2020-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20201202_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.CharField(choices=[('more than 10 lakh', 'more than 10 lakh'), ('5-10 Lakh', '5-10 Lakh'), ('Below 5 Lakh', 'Below 5 Lakh')], default='', max_length=100),
        ),
    ]
