# Generated by Django 2.2.14 on 2020-12-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_auto_20201202_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.CharField(choices=[('Below 5 Lakh', 'Below 5 Lakh'), ('5-10 Lakh', '5-10 Lakh'), ('more than 10 lakh', 'more than 10 lakh')], default='', max_length=100),
        ),
    ]
