# Generated by Django 2.2.14 on 2020-12-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_auto_20201202_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePic',
        ),
    ]
