# Generated by Django 2.2.14 on 2020-12-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_remove_userprofile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hq',
            field=models.CharField(choices=[('Pre-University', 'Pre-University'), ('Graduates Degree', 'Graduates Degree'), ('Masters Degree ', 'Masters Degree'), ('PhD', 'PhD'), ('Others', 'Others')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(choices=[('Public Sector', 'Public Sector'), ('Private Sector', 'Private Sector'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'UnEmployed'), ('Student', 'Student')], default='M', max_length=100),
        ),
    ]
